#version: "3.8"
services:
  db:
    image: postgres:15-alpine
    container_name: contact_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: contactdb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  server:
    build: ./server
    container_name: contact_server
    ports:
      - "5000:5000"
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'node -e "require(''http'').get(''http://localhost:5000/health'', res=>{process.exit(res.statusCode===200?0:1)}).on(''error'',()=>process.exit(1))"',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: db
      DB_NAME: contactdb
      DB_PORT: 5432
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    container_name: contact_client
    ports:
      - "8082:80"
    depends_on:
      - server

volumes:
  pgdata:
